
#include "minishell.h"

// — are called ASCII art, and specifically this style is known as a "FIGlet font".
//They are:
//Text rendered in blocky ASCII graphics, using characters like █, ║, ═, etc.
//Generated by FIGlet (short for Frank, Ian, and Glenn’s Letters), a tool that turns normal text into large, styled banners.
//The style I used above is a "ANSI Shadow" or "Big" font, which makes blocky uppercase letters look bold and powerful.

// Delay between characters (500 microseconds = 0.5ms)
void print_slowly(const char *line)
{
    int i;
    i = 0;
    while (line[i])
    {
        write(1, &line[i], 1);
        usleep(500);
        i++;
    }
}
void print_banner(void)
{
    const char *banner[] = {
        "\n",
        "\033[1;35m",
        "███╗   ███╗██╗███╗   ██╗██╗███████╗██╗  ██╗███████╗██╗     ██╗     \n",
        "████╗ ████║██║████╗  ██║██║██╔════╝██║  ██║██╔════╝██║     ██║     \n",
        "██╔████╔██║██║██╔██╗ ██║██║███████╗███████║█████╗  ██║     ██║     \n",
        "██║╚██╔╝██║██║██║╚██╗██║██║╚════██║██╔══██║██╔══╝  ██║     ██║     \n",
        "██║ ╚═╝ ██║██║██║ ╚████║██║███████║██║  ██║███████╗███████╗███████╗\n",
        "╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝\n",
        "\033[0m",
        "\n",
        NULL
    };
    int i = 0;
    while (banner[i])
    {
        print_slowly(banner[i]);
        usleep(80000); // 80ms between each line
        i++;
    }
}
